export const SETTING_THEME_LIGHT = 'light';
export const SETTING_THEME_DARK = 'dark';
export const SETTING_THEME_RETRO = 'retro';
export const SETTING_THEME_VALENTINE = 'valentine';
export const SETTING_THEME_HALLOWEEN = 'halloween';
export const SETTING_THEME_FOREST = 'forest';
export const SETTING_THEME_DRACULA = 'dracula';
export const SETTING_THEME_NIGHT = 'night';
export const SETTING_THEME_COFFE = 'coffee';
export const SETTING_THEME_WINTER = 'winter';

export const SETTING_THEME_ALL = [
	SETTING_THEME_LIGHT,
	SETTING_THEME_DARK,
	SETTING_THEME_RETRO,
	SETTING_THEME_VALENTINE,
	SETTING_THEME_HALLOWEEN,
	SETTING_THEME_FOREST,
	SETTING_THEME_DRACULA,
	SETTING_THEME_NIGHT,
	SETTING_THEME_COFFE,
	SETTING_THEME_WINTER
];
