export const AUTH_CURRENT_DATA_USER_REQUEST = 'AUTH_CURRENT_DATA_USER_REQUEST';
export const AUTH_CURRENT_DATA_USER_SUCCESS = 'AUTH_CURRENT_DATA_USER_SUCCESS';

export const AUTH_CURRENT_DATA_TOKEN_REQUEST = 'AUTH_CURRENT_DATA_TOKEN_REQUEST';
export const AUTH_CURRENT_DATA_TOKEN_SUCCESS = 'AUTH_CURRENT_DATA_TOKEN_SUCCESS';
