export const DASHBOARD_SHOW_DATA_REQUEST = 'DASHBOARD_SHOW_DATA_REQUEST';
export const DASHBOARD_SHOW_DATA_SUCCESS = 'DASHBOARD_SHOW_DATA_SUCCESS';

export const DASHBOARD_SHOW_LOADING_REQUEST = 'DASHBOARD_SHOW_LOADING_REQUEST';
export const DASHBOARD_SHOW_LOADING_SUCCESS = 'DASHBOARD_SHOW_LOADING_SUCCESS';
